controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:
    joints:
      - ur10shoulder_pan_joint
      - ur10shoulder_lift_joint
      - ur10elbow_joint
      - ur10wrist_1_joint
      - ur10wrist_2_joint
      - ur10wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    use_sim_time: true
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 1.0
      ur10shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur10shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur10elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur10wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur10wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur10wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
