<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Inertia parameters -->
  <xacro:property name="base_mass" value="2.0" />  <!-- This mass might be incorrect -->
  <xacro:property name="shoulder_mass" value="7.778" />
  <xacro:property name="upper_arm_mass" value="12.93" />
  <xacro:property name="forearm_mass" value="3.87" />
  <xacro:property name="wrist_1_mass" value="1.96" />
  <xacro:property name="wrist_2_mass" value="1.96" />
  <xacro:property name="wrist_3_mass" value="0.202" />

  <!-- These parameters are borrowed from the urcontrol.conf file
       but are not verified for the correct permutation.
       The permutation was guessed by looking at the UR5 parameters.
       Serious use of these parameters needs further inspection. -->
  <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
  <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
  <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
  <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
  <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
  <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <xacro:property name="ur10_d1" value="0.1273" />
  <xacro:property name="ur10_a2" value="-0.612" />
  <xacro:property name="ur10_a3" value="-0.5723" />
  <xacro:property name="ur10_d4" value="0.163941" />
  <xacro:property name="ur10_d5" value="0.1157" />
  <xacro:property name="ur10_d6" value="0.0922" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <xacro:property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
  <xacro:property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <xacro:property name="shoulder_height" value="${ur10_d1}" />
  <xacro:property name="upper_arm_length" value="${-ur10_a2}" />
  <xacro:property name="forearm_length" value="${-ur10_a3}" />
  <xacro:property name="wrist_1_length" value="${ur10_d4 - elbow_offset - shoulder_offset}" />
  <xacro:property name="wrist_2_length" value="${ur10_d5}" />
  <xacro:property name="wrist_3_length" value="${ur10_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="ur10_robot" params="parent prefix joint_limited
     shoulder_pan_lower_limit:=${-pi}    shoulder_pan_upper_limit:=${pi}
     shoulder_lift_lower_limit:=${-pi}    shoulder_lift_upper_limit:=${pi}
     elbow_joint_lower_limit:=${-pi}    elbow_joint_upper_limit:=${pi}
     wrist_1_lower_limit:=${-pi}    wrist_1_upper_limit:=${pi}
     wrist_2_lower_limit:=${-pi}    wrist_2_upper_limit:=${pi}
     wrist_3_lower_limit:=${-pi}    wrist_3_upper_limit:=${pi}">


    <joint name="cabinet_u10_joint" type="fixed">
      <parent link="${parent}" />
      <child link = "ur10_base_link" />
      <origin xyz="0.133 0.0 0.416" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="ur10_base_link" >
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/base.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/base.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="shoulder_pan_joint" type="revolute">
      <parent link="ur10_base_link" />
      <child link = "shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_pan_lower_limit}" upper="${shoulder_pan_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/shoulder.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/shoulder.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="shoulder_lift_joint" type="revolute">
      <parent link="shoulder_link" />
      <child link = "upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 -1.25 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${shoulder_lift_lower_limit}" upper="${shoulder_lift_upper_limit}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/upperarm.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/upperarm.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="elbow_joint" type="revolute">
      <parent link="upper_arm_link" />
      <child link = "forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 -1.95 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${elbow_joint_lower_limit}" upper="${elbow_joint_upper_limit}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/forearm.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/forearm.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="wrist_1_joint" type="revolute">
      <parent link="forearm_link" />
      <child link = "wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_1_lower_limit}" upper="${wrist_1_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/wrist1.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/wrist1.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="wrist_2_joint" type="revolute">
      <parent link="wrist_1_link" />
      <child link = "wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_2_lower_limit}" upper="${wrist_2_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/wrist2.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/wrist2.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="wrist_3_joint" type="revolute">
      <parent link="wrist_2_link" />
      <child link = "wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${wrist_3_lower_limit}" upper="${wrist_3_upper_limit}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="10.0"/>
    </joint>

    <link name="wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/wrist3.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://neo_simulation2/components/arms/ur10/meshes/wrist3.dae"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="ee_fixed_joint" type="fixed">
      <parent link="wrist_3_link" />
      <child link = "ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
          <parameters>$(find neo_simulation2)/configs/arms/joint_names_ur10_description.yaml  </parameters>
      </hardware>
    <joint name="shoulder_pan_joint">
      <command_interface name="position">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <command_interface name="velocity">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="shoulder_lift_joint">
      <command_interface name="position">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <command_interface name="velocity">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="elbow_joint">
      <command_interface name="position">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <command_interface name="velocity">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="wrist_1_joint">
      <command_interface name="position">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <command_interface name="velocity">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="wrist_2_joint">
      <command_interface name="position">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <command_interface name="velocity">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="wrist_3_joint">
      <command_interface name="position">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <command_interface name="velocity">
          <param name="min">-3.15</param>
          <param name="max">3.15</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
           <parameters>$(find neo_simulation2)/configs/arms/joint_names_ur10_description.yaml </parameters>
        </plugin>
    </gazebo>
  </xacro:macro>
</robot>
